mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views
app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/OMRCheck/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    name=models.CharField(max_length=5000, default="Barkha")

    def __str__(self):
        return self.choice_text

mysite/OMRCheck/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Choice, Question

'''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context={'latest_question_list':latest_question_list}
    return render(request, 'polls/index.html', context)


def details(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    context={'question': question}
    return render(request, 'polls/details.html',context )


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
'''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model=Question
    template_name = 'polls/details.html'


class ResultView(generic.DetailView):
    model=Question
    template_name = 'polls/results.html'


def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html',{'question':question, 'error_message':"You did'nt select a choice!"})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        #selected_choice.name=selected_choice.name+", "+question_id.name1
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))


    return HttpResponse("You are voting on question %s."%question_id)

mysite/polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
<p><strong>{{error_message}}</strong></p>
{% endif %}
<form action="{%url 'polls:vote' question.id%}" method="post">
    {% csrf_token %}
    Name : <input type="text" name="name1" id="username">
    <br>
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
            <!--<label for="choice{{forloop.counter}}">-->
            {{choice.choice_text}}
            </label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>